### ISSUE TITLE
Change on-laptop width in media querries

### ISSUE THREAD

**Issue by RavicharanN** [sharu725/hagura#18]
The home button overlaps with the heading when the window width is about 800-900 px.
So the on-laptop width needs to be changed to 1000px
![screen shot 2017-03-19 at 12 38 14 am](https://cloud.githubusercontent.com/assets/22046387/24075187/cdea076e-0c3c-11e7-8cae-09b50d9d94e0.png)

**Comment by sharu725** [comment]
Thanks @RavicharanN. Merged your PR.
