### ISSUE TITLE
Links are invisible in Firefox for Android

### ISSUE THREAD

**Issue by umpirsky** [sharu725/hagura#29]
![screenshot_2018-03-04-22-08-38](https://user-images.githubusercontent.com/208957/36950618-def4728a-1ff8-11e8-81bc-3f897545ec1b.png)

**Comment by sharu725** [comment]
I have missed out some vendor prefixes. Now fixed. Can you check again(please clear cache).

**Comment by umpirsky** [comment]
@sharu725 Worked, thanks! :champagne:
