### ISSUE TITLE
How to develop locally?

### ISSUE THREAD

**Issue by HarshBhatia** [sharu725/hagura#6]
I wanted to run this blog locally on my machine (mac osx) to quick preview my edits. How can I do that also I know nothing about ruby, that's why I can't figure out much.

**Comment by sharu725** [comment]
Mac comes with pre-installed ruby. So all you need to do is to install Jekyll.

`gem install jekyll `

(Maybe you should prefix sudo)
Then you should extract Hagura from zip. Open terminal inside the extracted folder and run

`jekyll serve`

You should see the site on this local URL

`127.0.0.1:4000/hagura/`

**Comment by HarshBhatia** [comment]
Okay, thanks it works!
